version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "Testing"
          command: echo "Hi"
add_ssh_keys: ssh -i "circle.pem" ubuntu@ec2-13-235-68-44.ap-south-1.compute.amazonaws.com